### PR TITLE
Set admin nickname for created events

### LINKED ISSUE #242: bug: Admin gets kicked out of events when joining from dashboard
### Bug Description

The admin gets kicked out of the event area when trying to get to slideshow or event page from dashboard

### Steps to Reproduce

1. Login as admin
2. Create an event
3. Try to go to the event page through the admin dashboard

### Expected Behavior

The admin can view the event as normal

### Actual Behavior

The admin gets kicked out or the app crashes

### Screenshots/Logs

```shell

```

### Operating System

Windows 11

### Version

0.1.0

### Browser (if applicable)

_No response_

### Additional Context

_No response_

### Impact

High - Significant impact on functionality

### Reproducibility

Always

### PR DESCRIPTION
**Pull request by GnisterDev**
### Description

This PR makes it so the admin that creates an event automatically gets added to the event with nickname "admin". This is to the admin can view the elements inside the event without getting kicked out.

### Type of Change

- **Bug fix** (non-breaking change which fixes an issue)
- **New feature** (non-breaking change which adds functionality)

### Related Issues

- Fixes #242

### Motivation and Context

The admin should be able to view the guest pages normally. This is currently not the case.

### Changes Made

- **`eventCookie.ts`** -- Extracted a new `createEventCookieValue` helper that signs a JWT. Refactored `setEventCookie` to delegate to this helper, removing duplicated signing logic.
- **`proxy.ts`** -- Added `attachAdminEventCookie` helper that uses `createEventCookieValue`. Admin users are now automatically granted access to event routes without going through the join flow.
- **`eventService.ts`** -- On successful event creation, automatically inserts a default `Admin` moderator user.
- **`config/admin.ts`** -- Exported `ADMIN_ID` constant (`"__adminUser"`).
- **`config/jwt.ts`** -- ``COOKIE_OPTIONS` export

### Checklist

- [x] My code follows the project's style guidelines
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published
- [x] I have checked my code for security vulnerabilities

### Additional Notes

A bug where events cannot be deleted when someone joins them has been discovered. This has been added as an issue.

### CODE REVIEW

File: apps/website/src/lib/utils/eventCookie.ts [hunk 1]
```diff
@@ -44,6 +45,19 @@ export function getEventCookie(
...
 }
 
+/**
+ * Signs a JWT and returns the cookie name + value + options.
+ * Safe to call from middleware (no dependency on next/headers).
+ */
+export function createEventCookieValue(
+  { eventId, userId, name, isModerator }: EventCookie,
+  secret: string
+): Result<{ name: string; value: string; options: typeof COOKIE_OPTIONS }, Error> {
```
Comment (igiwa001) [inline apps/website/src/lib/utils/eventCookie.ts]: I don't think it is a good idea to make a type dependent on a config value as it could change. Types should be declared explicitly.

File: apps/website/src/proxy.ts [hunk 2]
```diff
@@ -44,6 +68,15 @@ export default async function proxy(request: NextRequest): Promise<NextResponse>
       });
     }
 
+    const isAdmin = await verifyAccessToken()
+      .then(() => true)
+      .catch(() => false);
+    if (isAdmin) {
+      const response = NextResponse.redirect(new URL(`/events/${eventId}`, request.url));
+      attachAdminEventCookie(response, eventId);
```
Comment (igiwa001) [inline apps/website/src/proxy.ts]: Use `setEventCookie`.

File: apps/website/src/services/eventService.ts [hunk 3]
```diff
@@ -151,7 +152,13 @@ export class EventService {
             await this.dbService.db.delete(eventTable).where(eq(eventTable.id, event.id));
           })
       )
-      .onSuccess(() => this.dbService.flush());
+      .onSuccess(async event => {
+        this.dbService.db
+          .insert(userTable)
+          .values({ eventId: event.id, name: "Admin", isModerator: true })
```
Comment (igiwa001) [inline apps/website/src/services/eventService.ts]: Remember to insert the admin user with the static id.

**Review by igiwa001 — CHANGES_REQUESTED** [review]

File: apps/website/src/services/eventService.ts (hunk 3 above)
Comment (igiwa001) [reply apps/website/src/services/eventService.ts]: It doesn't work though. The admin cannot upload images. 

The `userId` in the database and the `userId` in the cookie do not match. This will cause uploading an image to fail, since it looks up the uploading user by the `userId` in the event-session cookie. In this case it tries uploading an image as the user with id `__adminUser` which does not exist.

You are right that setting a static id won't work since it is the primary key. Instead, I suggest we set the admin id based on the event id of the event they belong to (Something like "__admin-${eventId}"). This will enable us to infer the admin based on just the `eventId` and ensure the cookie and database match.

File: apps/website/src/lib/utils/eventCookie.ts [hunk 4]
```diff
@@ -51,7 +51,7 @@ export function getEventCookie(
  * @returns An empty result or an error.
  */
 export function setEventCookie(
-  { eventId, id: userId, name, isModerator }: User,
+  { eventId, id: userId, name, isModerator }: Omit<User, "joinedAt" | "lastAccessedAt">,
```
Comment (igiwa001) [inline apps/website/src/lib/utils/eventCookie.ts]: I think this is fine, though using `Pick` instead might be more future-proof as we won't need to change it if a new property is added to `User`.

**Review by igiwa001 — APPROVED** [review]
Looks good
