### PR TITLE
Fix: Remove dark mode flicker

### LINKED ISSUE #275: Bug: Light mode flickers on page refresh
### Bug Description

When the theme is set to dark, refreshing the page causes light mode to flicker for a split second, before the dark theme is applied.

### Steps to Reproduce

1. Select dark theme.
2. Refresh page.

### Expected Behavior

Page loads in dark mode.

### Actual Behavior

Page loads in light mode and then switches to dark mode.

### Screenshots/Logs

https://github.com/user-attachments/assets/134e30c2-3d67-4dac-802b-cf78b98f7666

### Operating System

NixOS 25.11

### Version

0.1.0

### Browser (if applicable)

Firefox 147.0.2

### Additional Context

_No response_

### Impact

High - Significant impact on functionality

### Reproducibility

Always

### PR DESCRIPTION
**Pull request by EnlightenedDan**
### Description

Resolved a FOUC (Flash Of Unstyled Content) bug in which reloading the page when `data-theme` is set to dark caused a brief "flicker"/"flash" to light mode before dark mode was re-applied

### Type of Change

- **Bug fix** (non-breaking change which fixes an issue)

### Related Issues

- Related to #275 

### Motivation and Context

The flicker was very noticeable and jarring, and made the page look slightly less polished

### Changes Made

- Stores users' preferred and resolved themes in cookies
- Make the `RootLayout` read the cookie and pre-render its HTML with the correct theme, avoiding FOUC
- Added some additional unit tests to `theme-utils.test.ts` to cover the new behavior

### How Has This Been Tested?

**Test Configuration**:

- **OS**: Windows 11
- **Version**: 0.1.0
- **Browser** (if applicable): Chrome & Firefox

**Test Details**:

Tested visually and by running unit tests

### Screenshots/Videos

https://github.com/user-attachments/assets/605a425b-4a80-42a2-9e3d-403b8bdd5086

### Checklist

- [x] My code follows the project's style guidelines
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published
- [x] I have checked my code for security vulnerabilities

### Additional Notes

- There will still be a brief flicker in cases where a page set to the dark mode is loaded in for the first time, because at that point, the theme has not yet been resolved
- Currently, the user's preference (Indicated by toggling to a specific theme) will always take precedence. If the user changes their system theme but does not delete cookies, the application's theme will not reflect the system-side change. If the current implementation of toggling between themes is replaced with a more comprehensive one that also offers the option to sync the application theme with the system theme, this should be altered.

### CODE REVIEW

File: apps/website/src/components/ConfigButtons/ThemeToggleButton.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ const ThemeToggleButton = () => {
       type="button"
       onClick={toggleTheme}
       className={`${styles.button} ${styles.left}`}
+      data-mounted={mounted ? "true" : "false"}
```
Comment (GnisterDev) [inline apps/website/src/components/ConfigButtons/ThemeToggleButton.tsx]: `mounted` is already a boolean. Also, setting this with css is verbose and can be done eaier by just doing `hidden={mounted}`. Change the css as well.

**Review by GnisterDev — CHANGES_REQUESTED** [review]
If your primary theme is `dark`, then the website flashes each time you refrsh until you switch from `dark` to `light` and then to `dark` again.

Also, if the theme is moved to the cookie, is there a point of having it in the localStorage?

File: apps/website/src/lib/theme-utils.ts [hunk 2]
```diff
@@ -48,24 +81,36 @@ export const getStoredTheme = (): Theme | null => {
...
+ * in sync with the current preference.
  *
  * @param {Theme} {@link theme} - If this equals `"system"`, a listener will be registered to track OS theme changes.
  * @returns {() => void} Cleanup function that removes the media query listener.
  */
-export const systemThemeListner = (theme: Theme) => {
-  if (theme !== "system") return () => {};
+export const systemThemeListener = (theme: Theme) => {
+  if (typeof window === "undefined" || theme !== "system") return () => {};
+  if (typeof window.matchMedia !== "function") return () => {};
```
Comment (igiwa001) [inline apps/website/src/lib/theme-utils.ts]: Could be combined into a single if ^

**Review by igiwa001 — CHANGES_REQUESTED** [review]
The preferred theme is not saved until the user manually toggles it with the button.

https://github.com/user-attachments/assets/7a8607d3-8336-408c-bd5b-ffa5bf15f392

File: apps/website/src/components/ConfigButtons/ThemeToggleButton.tsx (hunk 1 above)
Comment (igiwa001) [reply apps/website/src/components/ConfigButtons/ThemeToggleButton.tsx]: Hiding the component on the server causes it to appear some time after the page loads on the client. This should be removed. See https://github.com/IT2901-Group-2/foto-app/pull/290#discussion_r2962702649

**Review by GnisterDev — CHANGES_REQUESTED** [review]
It does not work correctly when you have no cookies.

It did this when i refreshed the page. I did *not* click the language button. It kinda looks like that in the video.

https://github.com/user-attachments/assets/b8fc9602-4a53-49d2-acb5-683a4323c805

File: apps/website/src/config/theme.ts [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+
+/**
+ * Type guard for resolved theme values.
+ * @param value - The stored resolved theme.
+ * @returns Whether the value is a valid resolved theme.
+ * Note: Resolved themes should only be "light" or "dark", never "system".
+ */
+export const isResolvedTheme = (value: unknown): value is ResolvedTheme => {
+  return typeof value === "string" && VALID_RESOLVED_THEMES.has(value as ResolvedTheme);
+};
```
Comment (GnisterDev) [inline apps/website/src/config/theme.ts]: This should be in `ThemeUtils`. These are utils. Not config.

Config is only for values.

File: apps/website/src/lib/utils/theme-utils.test.ts [hunk 4]
```diff
@@ -0,0 +1,334 @@
...
+    removeEventListener: vi.fn(),
+  };
+  const matchMedia = vi.fn().mockReturnValue(mediaQuery);
+  return { matchMedia, mediaQuery };
+}
+
+/* getSystemTheme */
+
+describe("getSystemTheme", () => {
+  afterEach(() => vi.unstubAllGlobals());
```
Comment (GnisterDev) [inline apps/website/src/lib/utils/theme-utils.test.ts]: This can be removed as it is in `main`

File: apps/website/src/lib/utils/theme-utils.test.ts [hunk 5]
```diff
@@ -0,0 +1,334 @@
...
+
+  beforeEach(() => {
+    ({ matchMedia, mediaQuery } = makeMatchMedia(false));
+    vi.stubGlobal("matchMedia", matchMedia);
+    document.documentElement.removeAttribute("data-theme");
+    document.documentElement.style.colorScheme = "";
+    document.cookie = `${THEME_RESOLVED_COOKIE_KEY}=`;
+  });
+
+  afterEach(() => vi.unstubAllGlobals());
```
Comment (GnisterDev) [inline apps/website/src/lib/utils/theme-utils.test.ts]: Remove this

**Review by GnisterDev — CHANGES_REQUESTED** [review]

**Review by GnisterDev — APPROVED** [review]

**Review by igiwa001 — APPROVED** [review]
